puxando o arquivo principal com a intalação do dataset

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import plotly.express as px
from sklearn.preprocessing import StandardScaler 

In [4]:
dataframe_credit = pd.read_csv("C:/Users/eyluc/Documents/ESTUDO -- 'data scientist'/Eydatascience/Estudos/Datasets/csv/credit_dt.csv")

In [5]:
display(dataframe_credit)

person_age  person_income person_home_ownership  person_emp_length  \
0              22          59000                  RENT              123.0   
1              21           9600                   OWN                5.0   
2              25           9600              MORTGAGE                1.0   
3              23          65500                  RENT                4.0   
4              24          54400                  RENT                8.0   
...           ...            ...                   ...                ...   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0             PERSONAL          D      35000          16.02            1   
1            EDUCATION          B       1000          11.14            0   
2              MEDICAL          C       5500          12.87            1   
3              MEDICAL          C      35000          15.23            1   
4              MEDICAL          C      35000          14.27            1   
...                ...        ...        ...            ...          ...   
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
0                     0.59                         Y   
1                     0.10                         N   
2                     0.57                         N   
3                     0.53                         N   
4                     0.55                         Y   
...                    ...                       ...   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
0                               3  
1                               2  
2                               3  
3                               2  
4                               4  
...                           ...  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30  

[32581 rows x 12 columns]

In [15]:
dataframe_credit.head(10)

person_age  person_income person_home_ownership  person_emp_length  \
0          22          59000                  RENT              123.0   
1          21           9600                   OWN                5.0   
2          25           9600              MORTGAGE                1.0   
3          23          65500                  RENT                4.0   
4          24          54400                  RENT                8.0   
5          21           9900                   OWN                2.0   
6          26          77100                  RENT                8.0   
7          24          78956                  RENT                5.0   
8          24          83000                  RENT                8.0   
9          21          10000                   OWN                6.0   

  loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
0    PERSONAL          D      35000          16.02            1   
1   EDUCATION          B       1000          11.14            0   
2     MEDICAL          C       5500          12.87            1   
3     MEDICAL          C      35000          15.23            1   
4     MEDICAL          C      35000          14.27            1   
5     VENTURE          A       2500           7.14            1   
6   EDUCATION          B      35000          12.42            1   
7     MEDICAL          B      35000          11.11            1   
8    PERSONAL          A      35000           8.90            1   
9     VENTURE          D       1600          14.74            1   

   loan_percent_income cb_person_default_on_file  cb_person_cred_hist_length  
0                 0.59                         Y                           3  
1                 0.10                         N                           2  
2                 0.57                         N                           3  
3                 0.53                         N                           2  
4                 0.55                         Y                           4  
5                 0.25                         N                           2  
6                 0.45                         N                           3  
7                 0.44                         N                           4  
8                 0.42                         N                           2  
9                 0.16                         N                           3

In [16]:

dataframe_credit.tail(8)

person_age  person_income person_home_ownership  person_emp_length  \
32573          56          90000              MORTGAGE                0.0   
32574          52          65004                  RENT                4.0   
32575          52          64500                  RENT                0.0   
32576          57          53000              MORTGAGE                1.0   
32577          54         120000              MORTGAGE                4.0   
32578          65          76000                  RENT                3.0   
32579          56         150000              MORTGAGE                5.0   
32580          66          42000                  RENT                2.0   

           loan_intent loan_grade  loan_amnt  loan_int_rate  loan_status  \
32573         PERSONAL          A       7200           6.17            0   
32574         PERSONAL          D      20000          15.58            1   
32575        EDUCATION          B       5000          11.26            0   
32576         PERSONAL          C       5800          13.16            0   
32577         PERSONAL          A      17625           7.49            0   
32578  HOMEIMPROVEMENT          B      35000          10.99            1   
32579         PERSONAL          B      15000          11.48            0   
32580          MEDICAL          B       6475           9.99            0   

       loan_percent_income cb_person_default_on_file  \
32573                 0.08                         N   
32574                 0.31                         Y   
32575                 0.08                         N   
32576                 0.11                         N   
32577                 0.15                         N   
32578                 0.46                         N   
32579                 0.10                         N   
32580                 0.15                         N   

       cb_person_cred_hist_length  
32573                          19  
32574                          19  
32575                          20  
32576                          30  
32577                          19  
32578                          28  
32579                          26  
32580                          30

In [18]:
dataframe_credit.describe()

person_age  person_income  person_emp_length     loan_amnt  \
count  32581.000000   3.258100e+04       31686.000000  32581.000000   
mean      27.734600   6.607485e+04           4.789686   9589.371106   
std        6.348078   6.198312e+04           4.142630   6322.086646   
min       20.000000   4.000000e+03           0.000000    500.000000   
25%       23.000000   3.850000e+04           2.000000   5000.000000   
50%       26.000000   5.500000e+04           4.000000   8000.000000   
75%       30.000000   7.920000e+04           7.000000  12200.000000   
max      144.000000   6.000000e+06         123.000000  35000.000000   

       loan_int_rate   loan_status  loan_percent_income  \
count   29465.000000  32581.000000         32581.000000   
mean       11.011695      0.218164             0.170203   
std         3.240459      0.413006             0.106782   
min         5.420000      0.000000             0.000000   
25%         7.900000      0.000000             0.090000   
50%        10.990000      0.000000             0.150000   
75%        13.470000      0.000000             0.230000   
max        23.220000      1.000000             0.830000   

       cb_person_cred_hist_length  
count                32581.000000  
mean                     5.804211  
std                      4.055001  
min                      2.000000  
25%                      3.000000  
50%                      4.000000  
75%                      8.000000  
max                     30.000000

In [7]:
dataframe_credit1 = dataframe_credit.drop(
    ['cb_person_cred_hist_length', 'loan_int_rate', 'loan_percent_income', 
     'person_home_ownership', 'loan_intent', 'loan_grade', 
     'cb_person_default_on_file', 'person_emp_length'],  
    axis=1
).rename(columns={
    "person_age": "age", 
    "person_income": "income", 
    "loan_amnt": "loan", 
    "loan_status": "default"
})

In [8]:
dataframe_credit1

age  income   loan  default
0       22   59000  35000        1
1       21    9600   1000        0
2       25    9600   5500        1
3       23   65500  35000        1
4       24   54400  35000        1
...    ...     ...    ...      ...
32576   57   53000   5800        0
32577   54  120000  17625        0
32578   65   76000  35000        1
32579   56  150000  15000        0
32580   66   42000   6475        0

[32581 rows x 4 columns]

In [9]:
dataframe_credit1.sum()

age            903621
income     2152784638
loan        312431300
default          7108
dtype: int64

In [109]:
dataframe_credit1[dataframe_credit1['age'] > 100]

age   income   loan  default
81     144   250000   4800        0
183    144   200000   6000        0
575    123    80004  20400        0
747    123    78000  20000        0
32297  144  6000000   5000        0

In [10]:
i = dataframe_credit1['age'] > 100
incorretos = []
corretos = []
for id, ii in enumerate(i):
  if ii == True: 
    incorretos.append(id)
  else: 
    corretos.append(id)

print(incorretos)

[81, 183, 575, 747, 32297]


In [11]:
dataframe_credit1.iloc[81, 183, 575, 747, 32297]

IndexingError: Too many indexers

In [12]:
for i in incorretos: 
  dt= dataframe_credit1.iloc[i]
  print(dt)
  print("\n")

age           144
income     250000
loan         4800
default         0
Name: 81, dtype: int64


age           144
income     200000
loan         6000
default         0
Name: 183, dtype: int64


age          123
income     80004
loan       20400
default        0
Name: 575, dtype: int64


age          123
income     78000
loan       20000
default        0
Name: 747, dtype: int64


age            144
income     6000000
loan          5000
default          0
Name: 32297, dtype: int64




In [13]:
dataframe_credit1['age'].mean()

np.float64(27.73459992019889)

In [14]:
dataframe_credit1.loc[dataframe_credit1['age'] > 100, 'age'] = 27

In [15]:
dataframe_credit1.isnull().sum()

age        0
income     0
loan       0
default    0
dtype: int64

In [16]:
type(dataframe_credit1)

pandas.core.frame.DataFrame

In [17]:
X_credit = dataframe_credit1.iloc[:, 0:3].values

In [18]:
X_credit

array([[    22,  59000,  35000],
       [    21,   9600,   1000],
       [    25,   9600,   5500],
       ...,
       [    65,  76000,  35000],
       [    56, 150000,  15000],
       [    66,  42000,   6475]], shape=(32581, 3))

In [19]:
type(X_credit)

numpy.ndarray

In [20]:
y_credit = dataframe_credit1.iloc[:, 3].values

In [21]:
y_credit

array([1, 0, 1, ..., 1, 0, 0], shape=(32581,))

In [22]:
type(y_credit)

numpy.ndarray

In [23]:
from sklearn.preprocessing import StandardScaler 
scaler_credit = StandardScaler()
X_credit = scaler_credit.fit_transform(X_credit)

In [24]:
X_credit[:,0].min(), X_credit[:,1].min(), X_credit[:,2].min()

(np.float64(-1.2439403067574821),
 np.float64(-1.0014952772370846),
 np.float64(-1.4377390104182448))

In [25]:
X_credit

array([[-0.9215897 , -0.11414329,  4.01940376],
       [-1.082765  , -0.91114671, -1.35864998],
       [-0.4380638 , -0.91114671, -0.64684875],
       ...,
       [ 6.00894829,  0.16012914,  4.01940376],
       [ 4.55837057,  1.35402091,  0.85584274],
       [ 6.17012359, -0.38841572, -0.49262515]], shape=(32581, 3))

In [26]:
from sklearn.model_selection import train_test_split 


In [27]:
X_credit_treinamento, X_credit_teste, y_credit_treinamento, y_credit_teste = train_test_split(X_credit, y_credit, test_size= 0.25, random_state= 0)

In [28]:
X_credit_treinamento

array([[-0.9215897 ,  0.22466383, -0.37003716],
       [ 0.36781271,  0.01492609,  0.06495248],
       [-0.4380638 , -0.1115619 ,  1.10892762],
       ...,
       [-0.9215897 , -0.44488358, -0.09322557],
       [-0.7604144 , -0.38841572,  0.06495248],
       [-0.7604144 , -0.5174851 ,  0.21522163]], shape=(24435, 3))

In [29]:
X_credit_teste

array([[-0.5992391 , -0.39970929, -1.13720071],
       [-0.5992391 ,  0.3053322 ,  2.43762325],
       [-0.5992391 ,  0.35373321, -0.56775973],
       ...,
       [ 0.36781271, -0.227079  , -0.09322557],
       [-0.5992391 ,  0.03105976, -0.56775973],
       [-0.4380638 , -0.03347493,  1.64673299]], shape=(8146, 3))

In [30]:
import pickle 

In [31]:
with open('credit.pkl', mode='wb') as f: 
  pickle.dump([X_credit_treinamento, y_credit_treinamento, X_credit_teste, y_credit_teste], f)